# Generated by Django 3.1.7 on 2021-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file', models.ImageField(upload_to='demo/static/input/')),
                ('fname', models.CharField(max_length=255)),
                ('binned', models.BooleanField(default=False)),
                ('gain', models.FloatField(default=1)),
            ],
        ),
    ]
