# Generated by Django 3.1.7 on 2021-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file', models.FileField(upload_to='demo/static/input/')),
                ('fname', models.CharField(default='', max_length=255)),
                ('in_path', models.CharField(default='', max_length=255)),
                ('out_path', models.CharField(default='', max_length=255)),
                ('binned', models.BooleanField(default=False)),
                ('gain', models.FloatField()),
                ('test_id', models.IntegerField(blank=True, default=None, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
