# Generated by Django 3.1.7 on 2021-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210322_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='out_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='in_file',
            field=models.ImageField(upload_to='demo/static/input/'),
        ),
    ]
