# Generated by Django 3.1.7 on 2021-03-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_imagefile_abbrv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='out_path',
            new_name='out_url',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='abbrv',
        ),
    ]
