# Generated by Django 3.1.7 on 2021-03-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210322_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='out_url',
        ),
    ]
