# Generated by Django 3.1.7 on 2021-03-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_remove_imagefile_out_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='fname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
